---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: yaml-lint
spec:
  description: |
    This task performs YAML linting on YAML files in a given Git repository. 
    It clones the specified repository at the given revision, then applies 
    linting rules to YAML files to identify potential syntax and formatting issues.
  params:
    - name: git-url
      description: The Git URL from which the test pipeline is originating. This can be from a fork or the original repository.
      type: string
    - name: git-revision
      description: The Git revision (commit SHA) from which the test pipeline is originating.
      type: string
    - name: remote-config-file
      description: |-
        The path to the YAML linting configuration file located in the Git repository.
        This configuration file specifies the rules and patterns for linting YAML files.
        It should be relative to the root of the repository.
      type: string
      default: ""
  steps:
    - name: clone-refs
      image: quay.io/konflux-qe-incubator/konflux-qe-tools:latest
      workingDir: /workspace
      script: |
        #!/bin/sh
        set -e

        git clone "$(params.git-url)" .
        git checkout "$(params.git-revision)"
    - name: yaml-lint
      image: quay.io/konflux-qe-incubator/konflux-qe-tools:latest
      workingDir: /workspace
      script: |
        #!/bin/sh
        set -e

        config_file=$(params.remote-config-file)
        if [ -z "$config_file" ]; then
          config_file="linter-config.yaml"
          cat <<EOF > $config_file
          yaml-files:
            - '*.yaml'
            - '*.yml'
          rules:
            braces: enable
            brackets: enable
            colons: enable
            commas: enable
            comments:
              require-starting-space: true
              ignore-shebangs: true
              min-spaces-from-content: 1
            comments-indentation: enable
            indentation: disable
            key-duplicates: enable
            line-length: disable
        EOF
        fi

        echo "INFO: $config_file configuration file has been created."
        cat $config_file

        yamllint -c $config_file .
