---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: register-cluster
spec:
  params:
    - name: host-url
      type: string
      description: The webhook url of the cluster
  steps:
    - name: register
      image: quay.io/konflux-qe-incubator/konflux-qe-tools:latest
      env:
        - name: SPRAYPROXY_SERVER_URL
          valueFrom:
            secretKeyRef:
              name: sprayproxy-secrets
              key: HOST_URL
        - name: SPRAYPROXY_SERVER_TOKEN
          valueFrom:
            secretKeyRef:
              name: sprayproxy-secrets
              key: TOKEN
      script: |
        #!/usr/bin/env bash
        set -o errexit
        set -o nounset
        set -o pipefail

        register_pac_server(){
          echo "Start registering PAC server [$(params.host-url)] to SprayProxy server"
          for _ in {1..5}; do
            if curl -k -X POST -H "Authorization: Bearer ${SPRAYPROXY_SERVER_TOKEN}" "${SPRAYPROXY_SERVER_URL}"/backends --data '{"url": "'"$(params.host-url)"'"}'; then
              break
            fi
            sleep 5
          done
        }

        list_pac_server(){
          echo "List PAC server from SprayProxy server"
          for _ in {1..5}; do
            if curl -k -X GET -H "Authorization: Bearer ${SPRAYPROXY_SERVER_TOKEN}" "${SPRAYPROXY_SERVER_URL}"/backends; then
              break
            fi
            sleep 5
          done
        }

        register_pac_server
        list_pac_server